#+LANGUAGE: ja
#+OPTIONS: \n:t author:nil creator:nil timestamp:nil html-postamble:nil toc:nil num:nil ^:{}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style1.css" />

#+TITLE: 1年生 後期 DirectX試験(第1回)

** 問１
*** その１
    4×4の単位行列を書け

*** その２
    3次元の情報(各ジオメトリの座標)を2次元の情報(スクリーン上の座標)に変換する過程で必要な変換処理3種類を書け

*** その３
    以下の機能はどの変換処理を用いて実現するか、それぞれについて答えよ
    1. ジオメトリの回転
    2. ジオメトリの拡大・縮小
    3. ジオメトリの平行移動
    4. カメラの回転
    5. カメラの移動
    6. ズームイン・ズームアウト


** 問２
*** その１
    以下は全て「D3DXMatrix」で始まるヘルパー関数である。それぞれの関数名を答えよ(D3DXMatrixは書かなくて良い)
     1. 単位行列作成
     2. 行列の積
     3. 平行移動行列作成（オフセット）
     4. X軸回転行列作成
     5. ビュー変換行列作成
     6. 射影変換行列作成

*** その２
     その１の5.の関数を使用する際に必要なパラメータを3つ書け。


** 問３
   以下は2Dの回転行列の求め方について書かれている。空白部を埋めよ

#+BEGIN_HTML
<pre>
xy平面上の点(x, y)を原点(0, 0)を中心にθ回転した点(x', y')について考える。

原点と(x, y)を通る直線とx軸のなす角をα、(x, y)と原点(0, 0)との距離をrとすると、

x' = <span class="bb"> </span>  …①
y' = <span class="bb"> </span>  …②

また、加法定理より、

cos(α + θ) = cosα・cosθ - sinα・sinθ  …③
sin(α + θ) = sinα・cosθ + cosα・sinθ  …④

x'について整理すると

x' = <span class="bb"> </span>  (∵①・③より)
   = <span class="bb"> </span>  (∵cosα = x/r、sinα = y/r)
   = <span class="bb"> </span>

同様にy'について整理すると

y' = <span class="bb"> </span>  (∵②・④より)
   = <span class="bb"> </span>  (∵sinα = y/r、cosα = x/r)
   = <span class="bb"> </span>

xy平面上の座標(x, y)を原点(0, 0)からのベクトルと考え、それを行列で表現すると
(x  y)
となり、この行列に2×2行列を掛けあわせたものは以下のようになる。

(x  y)・(a  c) = <span class="bb"> </span>   …⑤
        (b  d)

ここで、前述の「点(x, y)を原点を中心にθ回転させた点(x', y')」についても同様に行列で表現すると

(x'  y') = <span class="bb"> </span>   …⑥

⑤・⑥の右辺に注目し、
a = cosθ
b = -sinθ
c = sinθ
d = cosθ
と置くと、

(x  y)・(a  c) = (x  y)・<span class="bb"> </span>
        (b  d)

               = <span class="bb"> </span>
               = (x'  y')

と変換できる。

∴点(x, y)を原点を中心にθ回転させた点(x', y')は

(x  y)・<span class="bb"> </span>

にて求められる。
</pre>
#+END_HTML
