#+LANGUAGE: ja
#+OPTIONS: \n:t author:nil creator:nil timestamp:nil html-postamble:nil toc:nil num:nil ^:{}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style1.css" />

#+TITLE: 1年生 C++筆記試験(その１)

** 問１
以下のメンバを持つPlayerクラスを作成せよ。
・レベル、ヒットポイント、攻撃力、防御力(いずれもint型)
・上記メンバを初期化する関数
・上記メンバの値を表示する関数
・デフォルトコンストラクタ、デストラクタ(いずれも空関数で良い)

メンバ変数はカプセル化し、Playerクラスのメンバ関数以外からは
読み書きできないようにすること。


** 問２
レベルを指定しなければデフォルト値「１」がメンバ変数に設定され、
値を指定した場合はその値がメンバ変数に設定されるよう、
初期化関数の仕様をデフォルト引数を用いて変更せよ。


** 問３
問２で作成した初期化関数をオーバーロードし、４つのメンバ変数を固定値で初期化する引数無しの関数を作成せよ。


** 問４
問２・問３で作成した初期化関数を削除し、同等の機能をコンストラクタだけを用いて実現せよ。
その際、コンストラクタ内でメンバ変数に値を代入するのではなく、
メンバイニシャライザを用いること。


** 問５
Playerクラスと同じメンバを持つEnemyクラスを作成し、PlayerクラスとEnemyクラスにそれぞれ固有のメンバを追加するものとする。
ここで、PlayerクラスとEnemyクラスを汎化したCharacterクラスを作成せよ。
また、それに伴いPlayerクラスとEnemyクラスを修正せよ。


** 問６
PlayerクラスとEnemyクラスのインスタンスを生成する際、メンバの初期値の設定方法について以下の２つの案が考えられる。
１.インスタンスを生成する主体が初期値を指定する
２.PlayerクラスとEnemyクラスが初期値を指定する

それぞれに対応したコンストラクタを作成せよ。


** 問７
問６のそれぞれの案の長所・短所を述べよ。
